services:
  app:
    image: jkr-windows-breezy:latest
    build:
      context: .
      args:
        BUILD_ENV: prod
    container_name: jkr-windows-breezy
    volumes:
      - ./${GOOGLE_APPLICATION_CREDENTIALS}:/${GOOGLE_APPLICATION_CREDENTIALS}
      - ./data:/app/data
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /${GOOGLE_APPLICATION_CREDENTIALS}
      K_SERVICE: dev
      K_CONFIGURATION: dev
      K_REVISION: dev-00001

      BREEZY_EMAIL: ${BREEZY_EMAIL}
      BREEZY_PWD: ${BREEZY_PWD}

      PYTHON_ENV: prod

    ports:
      - '8080:8080'
    user: '0'
